// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23SaO5ct8pf5F4duJVXwiRtYcSIQoWo8',
    appId: '1:947639494240:web:7a29e8e55b9dacf9fd0505',
    messagingSenderId: '947639494240',
    projectId: 'pashuraktkosh',
    authDomain: 'pashuraktkosh.firebaseapp.com',
    storageBucket: 'pashuraktkosh.firebasestorage.app',
    measurementId: 'G-2GP9WDM7WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBq5dHLpkYnRvP9MwGgN_le0zaw-Ia33g',
    appId: '1:947639494240:android:2e2770189f554d56fd0505',
    messagingSenderId: '947639494240',
    projectId: 'pashuraktkosh',
    storageBucket: 'pashuraktkosh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfN7utmzoe0gGPjgLGCqak7RvU_jkiA8',
    appId: '1:947639494240:ios:bf69a11a7804ba5bfd0505',
    messagingSenderId: '947639494240',
    projectId: 'pashuraktkosh',
    storageBucket: 'pashuraktkosh.firebasestorage.app',
    iosBundleId: 'com.pashuraktkosh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfN7utmzoe0gGPjgLGCqak7RvU_jkiA8',
    appId: '1:947639494240:ios:bf69a11a7804ba5bfd0505',
    messagingSenderId: '947639494240',
    projectId: 'pashuraktkosh',
    storageBucket: 'pashuraktkosh.firebasestorage.app',
    iosBundleId: 'com.pashuraktkosh.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD23SaO5ct8pf5F4duJVXwiRtYcSIQoWo8',
    appId: '1:947639494240:web:8fdf97cb2371ec5bfd0505',
    messagingSenderId: '947639494240',
    projectId: 'pashuraktkosh',
    authDomain: 'pashuraktkosh.firebaseapp.com',
    storageBucket: 'pashuraktkosh.firebasestorage.app',
    measurementId: 'G-B70G5HE0K9',
  );
}
